name: envlogger-windows-build
on:
  workflow_dispatch:
    inputs:
      python-x:
        required: true
        default: 3
      python-y:
        required: true
        default: 10
      build:
        default: true
        type: boolean
      tag:
        required: true
        default: 1.0.8
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: deepmind/envlogger
      - uses: actions/checkout@v3
        with:
          path: build
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            gmp-devel
            mingw-w64-x86_64-gcc
          release: false
      - run: |
          echo "C:\msys64\usr\bin" >> $GITHUB_PATH
          echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
        shell: bash
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-x }}.${{ inputs.python-y }}
      - run: |
          xcopy /Y build
          xcopy build\patches patches
          bash -c "git apply -v *.diff"
          sed -i "s/cp310/cp${{ inputs.python-x }}${{ inputs.python-y }}/" envlogger\BUILD.bazel
          sed -i "s/1\.0\.8/${{ inputs.tag }}/" envlogger\BUILD.bazel
          curl -O https://storage.googleapis.com/google-code-archive-source/v2/code.google.com/mman-win32/source-archive.zip
          C:\Windows\System32\tar.exe -xf source-archive.zip mman-win32/trunk
          cd mman-win32\trunk
          bash ./configure --libdir=/mingw64/lib --incdir=/mingw64/include/sys
          make
          make install
        shell: cmd
      - run: |
          bazel test --compiler=mingw-gcc --define cpu=haswell --test_output=errors --verbose_failures envlogger/...
        if: ${{ inputs.build == false }}
        env:
          BAZEL_SH: C:\msys64\usr\bin\bash.exe
        shell: cmd
      - run: |
          bazel build --compiler=mingw-gcc --define cpu=haswell --test_output=errors --verbose_failures envlogger:package
        if: ${{ inputs.build == true }}
        env:
          BAZEL_SH: C:\msys64\usr\bin\bash.exe
        shell: cmd
      - run: |
          gh release upload ${{ inputs.tag }} bazel-bin/envlogger/*.whl --clobber -R ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash